### PR TITLE
Improve packing naming

### PR DESCRIPTION
**Pull request by lockieRichter**
- Updates the `com.shockbytes.dante` directory to be named `src`. Using Java package naming conventions in this project isn't good practice for Dart, where the main code normally lives under `lib/src`.
- Fixes a few typos in the README.
- Adds Flutter Lints to the project. This will help enforce best practice throughout the lifecycle of the project.

### CODE REVIEW

**Review by shockbytes — APPROVED** [review]
Nicely done!

**Comment by lockieRichter** [comment]
Thanks 😎

**Comment by shockbytes** [comment]
You can merge it.

**Comment by lockieRichter** [comment]
I don't have permissions to merge, only people with write access to the repo can merge PRs.

**Pull request merged**
